server:
  port: ${SERVER_PORT:0}

management:
  security:
    enabled: false
  endpoints:
    web.exposure.include: '*'
    web.enabled: true
    enabled-by-default: true
  endpoint:
    env.enabled: true
    auditevents.enabled: true
    beans.enabled: true
    conditions.enabled: true
    configprops.enabled: true
    health.enabled: true
    heapdump.enabled: true
    info.enabled: true
    logfile.enabled: true
    mappings.enabled: true
    loggers.enabled: true
    metrics.enabled: true
  health:
    db.enabled: true
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

eureka:
  client:
    healthcheck:
      enabled: true

spring:
  jpa:
    generate-ddl: false
  hibernate:
    ddl-auto: create-drop
    show_sql: true
    use_sql_comments: false
    format_sql: false

---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}

security:
  basic:
    enabled: false
